from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('demo/click/', views.demo_click),
    path('demo/trigger/hover/', views.trigger_hover),
    path('demo/trigger/delay/', views.trigger_delay),
    path('demo/trigger/keyup/', views.trigger_keyup),
    path('demo/swap/<str:mode>/', views.swap_mode),
    path('demo/slow/', views.slow_response),
    path('demo/list/', views.list_items),
    path('demo/list/<int:idx>/', views.delete_item),
    path('demo/page-a/', views.page_a),
    path('demo/page-b/', views.page_b),
    path('demo/vals/', views.vals_demo),
    path('demo/progress/start/', views.progress_start),
    path('demo/progress/poll/', views.progress_poll),
    path('demo/oob/', views.oob_swap),
    path('demo/inline/', views.inline_edit),
    path('demo/inline/form/', views.inline_edit_form),
    path('demo/infinite/', views.infinite_scroll),
    path('demo/models/', views.cascading_models),
    path('demo/validate/', views.validate_email),
    path('demo/search/', views.active_search),
    path('demo/select/', views.select_demo),
    path('demo/preserve/', views.preserve_demo),
    path('demo/sortable/', views.sortable_reorder),
    path('demo/upload/', views.file_upload),
    path('demo/prompt/', views.prompt_demo),
    path('demo/headers/', views.headers_demo),
    path('demo/sync/', views.sync_demo),
    path('demo/replace_url/', views.replace_url_demo),
    path('demo/params/', views.params_demo),
    path('demo/disable/', views.disable_demo),
    path('demo/error/', views.response_targets_demo),
    path('demo/rest/', views.rest_verbs_demo),
]